### PR TITLE
Feature/66 Sphinx Documentation

### PR DESCRIPTION
**Pull request by damian-romero**
**Description**

See #66

**ToDo List**

 - [x] Check conflicts with develop. This branch was created before #70 
 - [x] Create a GitHub Action script

**Test plan**

Test correct badge message after the build is ready in Read the Docs.

*Resources*

Hyperlinks in `.rst` docs work differently than the ones in Markdown. Resource:
https://stackoverflow.com/questions/45499108/if-possible-how-do-we-put-hyperlink-within-the-code-section-in-rst-files

*Screenshots or additional context*

#### Original README.md file
Original README.md file
#### Same section, converted using Pandoc
Same section, converted using Pandoc
#### Same section, manual update
Same section, manual update

### CODE REVIEW

**Comment by damian-romero** [comment]
Note that commit [9387eb1](https://github.com/UAL-ODIS/ReQUIAM_csv/pull/74/commits/9387eb1b521bc38d96f686655fcdb58d9295d198) fixes a minor error in `.gitignore` which I introduced in [0ac5149](https://github.com/UAL-ODIS/ReQUIAM_csv/pull/74/commits/0ac51494d314c7b47df5249c75c8b0d56900a72e) when I was trying to use VSCode's Python Docstring Generatior. I raised an [issue](https://github.com/NilsJPWerner/autoDocstring/issues/178) with them.

**Comment by damian-romero** [comment]
Seems to have no conflicts with Develop

**Comment by damian-romero** [comment]
@astrochun I made one last change: instead of trying to simplify the REDME.md file here, I have created a new issue #75. 

This PR should now be ready for your creating a GitHub Action script for RTDs and for your code review.

**Comment by astrochun** [comment]
> @astrochun I made one last change: instead of trying to simplify the REDME.md file here, I have created a new issue #75.
> 
> This PR should now be ready for your creating a GitHub Action script for RTDs and for your code review.

Yes, but it seems that you created a bug issue for #75 when it isn't. It's merely documentation.

**Review by astrochun — CHANGES_REQUESTED** [review]
A few changes are needed that I will implement:

- [x] Add GitHub Action
- [x] Fix GitHub badges URL (post-migration from `ualibraries` to `UAL-ODIS`)
- [x] Change .rst file namespaces to all lowercase
- [x] Adjust API Documentation indexing
- [x] Update docstrings in modules, etc.

**Review by damian-romero — COMMENTED** [review]
All changes look good. I tested the documentation and it's working well. I think it's ready to be merged into develop.

**Review by astrochun — APPROVED** [review]

**Pull request merged**
