### PR TITLE
feature/gh_actions_build_test

### PR DESCRIPTION
**Pull request by astrochun**
See #57
﻿
Includes minor fix for #56

### CODE REVIEW

**Review by astrochun — COMMENTED** [review]
Changes look good and all CI build tests have passed

**Review by damian-romero — COMMENTED** [review]
For `.github/workflows/python-package.yml`
- Do we need to trigger the job on pull-requests? I would think a build on push is enough.

**Comment by astrochun** [comment]
> For `.github/workflows/python-package.yml`
> 
> * Do we need to trigger the job on pull-requests? I would think a build on push is enough.

We do and here's why: `pull_request` trigger will merge those changes into whichever receiving branch (`master` or `develop`), assuming there's not conflict. It will check downstream whether the code will compile. If you look at the logs, you will see that the `push` is based on the latest commit hash, but the `pull_request` is not.

**Comment by damian-romero** [comment]
- Testing with `[act](https://github.com/nektos/act)` looks good
- Reviewed all files
- Ready for merge

**Pull request merged**
